set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "SSE: cpack-exercise-wt2223 solution")
set(CPACK_PACKAGE_VENDOR "SSE 2022-23")
set(CPACK_PACKAGE_MAINTAINERS "Vidushi Arora")
set(CPACK_PACKAGE_CONTACT "st180416@stud.uni-stuttgart.de")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/arora-vidushi/cpack-exercise-wt2223")

set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_STRIP_FILES TRUE)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS YES)

set(CPACK_GENERATOR "TGZ;DEB")
include(CPack)